# An example configuration file for General Spatial Transcriptomics pipeline for Xenium dataset

log_level = "INFO" # Define the logging level here. Options are: DEBUG, INFO, WARNING, ERROR, CRITICAL
seed = 21122023    # Random seed for reproducibility

[project]
analysis_name = "Tisku"
data_type = "Xenium"

[io]
base_dir = "."                         # Base directory for the project (relative to the current working directory)
dataset_id = ""                
output_dir = "analysis"                # Directory where the output will be saved (relative to base_dir)
dataset_dir = "data/Tisku"                  # Directory containing dataset (Xenium / CosMx) (relative to data_dir)
zarr_dir = "data/Tisku.zarr"               # Directory where Zarr data will be stored (relative to data_dir)
area_path = "selected_cells_stats.csv" # Path to the CSV file containing selected cells statistics (relative to data_dir) # only for Xenium?
logging_path = "logs"                  # Directory where logs will be saved (relative to output_dir)

[pipeline]
modules = [
    "0_format",
    "1_QualityControl",
    "2_DimensionReduction",
    "3_Annotate",
    "4_ViewImages",
    "5_SpatialStat",
    "6_MuSpan"
]

[modules.QualityControl]
min_counts = 10 # Minimum number of counts required for a cell to pass filtering
min_cells = 5 # Minimum number of cells expressed required for a gene to pass filtering
min_dapi = '' # Minimum mean DAPI intensity required for a gene to pass filtering (CosMx)


[modules.DimensionReduction]
n_comps = 50  # number of principal components to compute                        
n_neighbors = [10, 15, 20]  # number of neighbors for the neighborhood graph                    
resolution = [0.1, 0.3, 0.5]  # resolution for leiden clustering                  
cluster_name = "leiden"  # name of the cluster column in adata.obs  

[modules.Annotate]
new_clusters = "cell_type" 

[modules.ViewImages]
gene_list = [ # List of genes to visualize on tissue
    "EPCAM",
    "CD3D",
    "CD68",
    "PTPRC",
    "ACTA2",
]

[modules.MuSpan]
fov = '' # only for CosMx

transcripts = [ # List of genes to visualize on tissue
    "EPCAM",
    "CD3D",
    "CD68",
    "PTPRC",
    "ACTA2",
]

#adata cell id is 'cell_id' in Xenium and 'Cell_ID' in CosMx
cluster_labels = "cell_type"

min_edge_distance = 0
max_edge_distance = 45
distance_list = [10, 20, 50]
min_edge_distance_shape = 0
max_edge_distance_shape = 1
k_list = [2, 5, 10, 15]

# Path to the CSV file containing selected cells statistics (relative to data_dir) for Xenium only?
area_path = "Xenium_SelectedCells.csv" 

