log_level = "INFO"
seed = 21122023

[project]
analysis_name = "tyler_proseg"
slide_name = "Slide_1" 
data_type = "CosMx"

[io]
base_dir = "."
dataset_id = "TylerWooldridgeSlide1"
dataset_dir = "data/tyler_1"
zarr_dir = "data/tyler_1.zarr"

[pipeline]
modules = ["0_format", "1_QualityControl"]

[modules.QualityControl]
min_counts = 50 
min_cells = 5 
min_genes = 40 
min_area = 5 
max_area = 100  
fov_metadata_path = "data/tyler_1/TylerWooldridgeSlide1_fov_cohort.csv"
proseg_zarr_path = "data/tyler1_proseg.zarr" 
proseg_cell_id_col = "original_cell_id"
original_cell_id_col = "cell"  