# An example configuration file for General Spatial Transcriptomics pipeline for CosMx dataset

log_level = "INFO" # Define the logging level here. Options are: DEBUG, INFO, WARNING, ERROR, CRITICAL
seed = 21122023    # Random seed for reproducibility

[project]
analysis_name = "Kitam" # sets the name of your analysis folder
data_type = "CosMx" # Xenium or CosMx

[io]
base_dir = "."                         # Base directory for the project (relative to the current working directory)
dataset_id = "Quarter"               # specific to cosmx
dataset_dir = "data/Kitam"                  # Directory containing dataset (Xenium / CosMx) (relative to data_dir)
zarr_dir = "data/Kitam.zarr"               # Directory where Zarr data will be stored (relative to data_dir)
logging_path = "logs"                  # Directory where logs will be saved (relative to output_dir)

[pipeline]
modules = [
    "0_format",
    "1_QualityControl",
    "2_DimensionReduction",
    "3_Annotate",
    "4_ViewImages",
    "5_SpatialStat",
    "6_MuSpan"
]

[modules.QualityControl]
min_counts = 50 # Minimum number of counts required for a cell to pass filtering
min_cells = 5 # Minimum number of cells expressed required for a gene to pass filtering
min_dapi = 100 # Minimum mean DAPI intensity required for a gene to pass filtering (CosMx)


[modules.DimensionReduction]
n_comps = 50  # number of principal components to compute     
n_pca = 30 # no of PCs for UMAP                   
n_neighbors = [30, 50]  # List of neighbors to test                    
resolution = [1.0, 2.0]  # List of resolutions to test                  
cluster_name = "leiden"  # name of the cluster column in adata.obs  

[modules.Annotate]
chosen_cluster = "leiden_n50_r1.0"  # Put the exact name of the one you liked best

ScType_anno =  true # true / false
ScType_mode = "All" # All or one (chosen cluster)
ScType_custom_db = "" # use when using custom marker list
ScType_tissue = "Brain" # remove if using custom marker list

CellTypist_anno = true # true / false
CellTypist_mode = "All" # All or one (chosen cluster)
CellTypist_model = "Mouse_Whole_Brain"

[modules.ViewImages]
gene_list = [ # List of genes to visualize on tissue
    "Nrgn",
    "Plp1",
    "Plpp3",
    "Bsg",
    "Tcf7l2",
]

[modules.MuSpan]
transcripts = [ # List of genes to visualize on tissue
    "Nrgn",
    "Plp1",
    "Plpp3",
    "Bsg",
    "Tcf7l2",
]


min_edge_distance = 0
max_edge_distance = 200
distance_list = [50, 90, 120]
min_edge_distance_shape = 0
max_edge_distance_shape = 1
k_list = [2, 5, 10, 15]


# For cosmx custom cell selection 
selection_name = "phageku" # the selection csv will be named this
selected_celltypes = ["10", "14", "5", "18"] # selected clusters (based on chosen cluster) to visualize in MuSpan
selected_fovs = ["33", "32", "28", "29"] # selected boxes (based ROI plot from View Images module) to visualize in MuSpan
cell_types = [14, 18] # two clusters (based on chosen cluster) for pair spatial stat comparison. Must be 2 from selected_celltypes