
[project]
analysis_name = "test_run"
data_type = "CosMx"

[pipeline]
modules = ["1_QualityControl", "2_DimensionReduction"]

[io]
dataset_dir = "fake/path"
dataset_id = "fake_id"
zarr_dir = "fake/path.zarr"
    