log_level = "INFO"
seed = 21122023

[project]
analysis_name = "pCosMx"
data_type = "CosMx"

[io]
base_dir = "."
# Point this to the main folder containing all your dataset subfolders
base_raw_dir = "data/set1"
base_zarr_dir = "data/set1_zarrs" 

[pipeline]
modules = ["0_format", "1_QualityControl"]

[modules.QualityControl]
min_counts = 50 
min_cells = 5 
min_genes = 40 
min_area = 1500
max_area = 15000
min_dapi = 100

fov_metadata_path = "data/set1/{slide_name}/{slide_name}_fov_cohort.csv"
metadata_join_col = "fov"
